export enum OrderStatus   {
  ORDERED = "ORDERED",
  PREPARING = "PREPARING",
  READY = "READY",
  SERVED = "SERVED",
  DELIVERED = "DELIVERED",
  PAID = "PAID",
  CANCELLED = "CANCELLED",
  AVAILABLE = "AVAILABLE",
  COMPLETED = "COMPLETED",
};
